export const homeObjOne = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Członkowstwo',
    headline: 'Zarezerwuj miejsce',
    description: 'Nasi członkowie mogą bezpłatnie rezerwować miejsca w kinie, sprawdź to już teraz',
    imgStart: true,
    img: require('../../images/svg-2.svg').default,
    alt: 'car',
    dark: false,
    primary: false,
    darkText: true,
};

export const homeObjTwo = {
    id: 'signup',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Rejestracja',
    headline: 'Zarejestruj się już dziś',
    description: 'Zarejestruj się aby korzystać ze wszystkich funkcji ',
    imgStart: true,
    img: require('../../images/svg-3.svg').default,
    alt: 'car',
    dark: false,
    primary: false,
    darkText: true,
};
